CREATE USER deploy WITH LOGIN PASSWORD 'deploy';
ALTER ROLE deploy CREATEDB;

CREATE DATABASE dev_db;
CREATE DATABASE prd_db;

GRANT ALL PRIVILEGES ON DATABASE dev_db TO deploy;
GRANT ALL PRIVILEGES ON DATABASE prd_db TO deploy;
